### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by lupa18** [drnoa/sqlledger_docker#2] opened 2016-11-22 19:14 UTC
I'm getting error:
web_1  | /usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
web_1  |   'Supervisord is running as root and it is searching '
web_1  | 2016-11-22 19:10:27,049 CRIT Supervisor running as root (no user in config file)
web_1  | 2016-11-22 19:10:27,050 WARN Included extra file "/etc/supervisor/conf.d/supervisord-apache2.conf" during parsing
web_1  | 2016-11-22 19:10:27,050 WARN Included extra file "/etc/supervisor/conf.d/supervisord-postgresql.conf" during parsing
web_1  | 2016-11-22 19:10:27,064 INFO RPC interface 'supervisor' initialized
web_1  | 2016-11-22 19:10:27,064 CRIT Server 'unix_http_server' running without any HTTP authentication checking
web_1  | 2016-11-22 19:10:27,064 INFO supervisord started with pid 1
web_1  | 2016-11-22 19:10:28,067 INFO spawned: 'postgres' with pid 10
web_1  | 2016-11-22 19:10:28,071 INFO spawned: 'apache2' with pid 11
web_1  | 2016-11-22 19:10:28,081 INFO exited: postgres (exit status 127; not expected)
web_1  | 2016-11-22 19:10:29,157 INFO spawned: 'postgres' with pid 79
web_1  | 2016-11-22 19:10:29,158 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1  | 2016-11-22 19:10:29,169 INFO exited: postgres (exit status 127; not expected)
web_1  | 2016-11-22 19:10:31,173 INFO spawned: 'postgres' with pid 81
web_1  | 2016-11-22 19:10:31,183 INFO exited: postgres (exit status 127; not expected)
web_1  | 2016-11-22 19:10:34,189 INFO spawned: 'postgres' with pid 83
web_1  | 2016-11-22 19:10:34,199 INFO exited: postgres (exit status 127; not expected)
web_1  | 2016-11-22 19:10:35,201 INFO gave up: postgres entered FATAL state, too many start retries too quickly

also you talk about:
 docker logs postgresql

but with your instructions there is no such as postgresql container

also you talk about password for first login ... and user?

thanks in advance!

**Comment by drnoa** [comment] 2016-12-01 14:18
Hi lupa18

I updated the readme.md file. There were some copy/paste errors. It is maybe still not complete or outdated. And I reproduced the error you wrote. Maybe it is because of some updates inside the container. I am trying to fix the container and will upload it again. I will give you feedback as soon i got the solution.

**Comment by drnoa** [comment] 2016-12-02 20:03
Hi lupa18
I figured out where the error was. In the newer Versions of the ubuntu source package there is sudo not installed by default. But the container use sudo to change to the postgres user. So checked in a new version of the dockerfile. The docker hub build will be newly generated in some minutes.

**Closed as completed by drnoa** 2016-12-02 20:03 UTC

**Comment by lupa18** [comment] 2016-12-02 21:14
thanks !
